version: 2.1

orbs:
  github-release: haskell-works/github-release@1.3.3
  win: circleci/windows@5.0

jobs:
  build-windows:
    executor:
      name: win/server-2022
      shell: pwsh.exe
      size: large
    steps:
      - run:
            name: Install cmake
            command: choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
            
      - run: |
          dir "C:\Program Files\CMake\"
          dir "C:\Program Files\Cmake\bin"
          dir "C:\Program Files"
          dir "C:\Program Files\ninja"
        
      - run:
            name: Install ninja
            command: choco install -y ninja
            
      - checkout
      
      - run:
            name: Update submodules
            command: |
              git submodule sync
              git submodule update --init

      - run:
            name: Configure dorito
            working_directory: dorito
            command: |
                mkdir build
                cd build
                cmake -G Ninja ..
      - run:
            name: Build dorito
            working_directory: dorito/build
            command: ninja
                
      - run:
            name: Package dorito
            working_directory: dorito/build
            command: ninja package
            
      - persist_to_workspace:
          root: ./dorito/build
          paths:
            - Dorito.zip

      - store_artifacts:
          path: doritio/build/Dorito.zip

  build-macos:
    macos:
      xcode: 13.4.1
    resource_class: macos.x86.medium.gen2
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run:
          name: Install pkg-config
          command: brew install pkg-config
      - run:
          name: Install cmake
          command: brew install cmake
      - run:
          name: Install ninja
          command: brew install ninja
      - run:
          name: Checkout dorito
          command: git clone --recurse-submodules "$CIRCLE_REPOSITORY_URL"
      - run:
          name: Configure dorito
          working_directory: dorito
          command: |
            mkdir build
            cd build
            cmake -G Ninja ..
      
      - run:
          name: Awful Kludge
          command: |
            mkdir  /Users/distiller/project/kludge
            ln -s /usr/local/bin/python3 /Users/distiller/project/kludge/python

      - run:
          name: Build dorito
          working_directory: dorito/build
          command: |
            export PATH=$PATH:/Users/distiller/project/kludge
            ninja
               
      - run:
          name: Package dorito
          working_directory: dorito/build
          command: ninja package
            
      - persist_to_workspace:
          root: ./dorito/build
          paths:
           - Dorito.dmg

      - store_artifacts:
          path: dorito/build/Dorito.dmg

workflows:
  version: 2
  build-release:
    jobs:
      - build-windows
      #- build-macos
