version: 2.1

orbs:
  github-release: haskell-works/github-release@1.3.3
  win: circleci/windows@5.0

jobs:
  build-windows:
    executor:
      name: win/server-2022
      shell: bash.exe
      size: large
    steps:
      - run:
            name: Install cmake
            command: choco install -y cmake
      - run:
            name: Install ninja
            command: choco install -y ninja
      - run:
            name: Checkout dorito
            command: git clone --recurse-submodules git@github.com:lesharris/dorito.git
      - run:
            name: Configure dorito
            working_directory: dorito
            command: |
                mkdir build
                cd build
                cmake -G Ninja ..
      - run:
            name: Build dorito
            working_directory: dorito/build
            command: ninja
                
      - run:
            name: Package dorito
            working_directory: dorito/build
            command: ninja package
            
      - persist_to_workspace:
          root: dorito/build
          paths:
            - Dorito-0.5.0-win32.zip

      - store_artifacts:
          root: dorito/build
          path: Dorito-0.5.0-win32.zip

  build-macos:
    macos:
      xcode: 13.4.1
    resource_class: macos.x86.medium.gen2
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
     # - run:
     ##       name: Install pkg-config
       #     command: brew install pkg-config
     # - run:
      #      name: Install cmake
       #     command: brew install cmake
     # - run:
      #      name: Install ninja
       #     command: brew install ninja
    #  - run:
    ##        name: Checkout dorito
      #      command: git clone --recurse-submodules "$CIRCLE_REPOSITORY_URL"
     # - run:
     #       name: Configure dorito
     #       working_directory: dorito
     #       command: |
     #           mkdir build
     #           cd build
     #           cmake -G Ninja ..
                
      - run: echo `which python`
      - run: echo `which python3`
      - run: echo `pwd`
      
      - run:
        name: Awful Kludge
        command: |
          mkdir  /Users/distiller/project/kludge
          ln -s /usr/local/bin/python3 /Users/distiller/project/kludge/python
          PATH=$PATH:/Users/distiller/project/kludge
          
      - run: echo `which python`
   #   - run:
   ##         name: Build dorito
   #         working_directory: dorito/build
   #         command: ninja
               
   #   - run:
   #         name: Package dorito
   #         working_directory: dorito/build
   #         command: ninja package
            
   #   - persist_to_workspace:
   #       root: ./dorito/build
   #       paths:
   #         - Dorito-0.5.0-Darwin.dmg

    #  - store_artifacts:
    #      root: ./dorito/build
    #      path: Dorito-0.5.0-Darwin.dmg

workflows:
  version: 2
  build-release:
    jobs:
     # - build-windows
      - build-macos
