version: 2.1

orbs:
  github-release: haskell-works/github-release@1.3.3
  win: circleci/windows@5.0

jobs:
  build-windows:
    executor:
      name: win/server-2022
      shell: pwsh.exe
      size: large
    steps:
      - run: |
          dir env:
   #   - run:
    #        name: Install cmake
     #       command: choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
     # - run:
      #      name: Install ninja
       #     command: choco install -y ninja
            
    #  - run:
    #      name: Setup .ssh
    #      command: |
    #        mkdir .ssh
    #        New-Item .ssh/known_hosts
    ##        Add-Content -Path .ssh/known_hosts -Value github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      #      Add-Content -Path .ssh/known_hosts -Value github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
      #      Add-Content -Path .ssh/known_hosts -Value github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      #      Add-Content -Path .ssh/known_hosts -Value bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
      #      Add-Content -Path .ssh/known_hosts -Value gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=

      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
            name: Configure dorito
            working_directory: dorito
            command: |
                mkdir build
                cd build
                cmake -G Ninja ..
      - run:
            name: Build dorito
            working_directory: dorito/build
            command: ninja
                
      - run:
            name: Package dorito
            working_directory: dorito/build
            command: ninja package
            
      - persist_to_workspace:
          root: ./dorito/build
          paths:
            - Dorito.zip

      - store_artifacts:
          path: doritio/build/Dorito.zip

  build-macos:
    macos:
      xcode: 13.4.1
    resource_class: macos.x86.medium.gen2
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run:
          name: Install pkg-config
          command: brew install pkg-config
      - run:
          name: Install cmake
          command: brew install cmake
      - run:
          name: Install ninja
          command: brew install ninja
      - run:
          name: Checkout dorito
          command: git clone --recurse-submodules "$CIRCLE_REPOSITORY_URL"
      - run:
          name: Configure dorito
          working_directory: dorito
          command: |
            mkdir build
            cd build
            cmake -G Ninja ..
      
      - run:
          name: Awful Kludge
          command: |
            mkdir  /Users/distiller/project/kludge
            ln -s /usr/local/bin/python3 /Users/distiller/project/kludge/python

      - run:
          name: Build dorito
          working_directory: dorito/build
          command: |
            export PATH=$PATH:/Users/distiller/project/kludge
            ninja
               
      - run:
          name: Package dorito
          working_directory: dorito/build
          command: ninja package
            
      - persist_to_workspace:
          root: ./dorito/build
          paths:
           - Dorito.dmg

      - store_artifacts:
          path: dorito/build/Dorito.dmg

workflows:
  version: 2
  build-release:
    jobs:
      - build-windows
      #- build-macos
