version: 2.1

orbs:
  github-release: haskell-works/github-release@1.3.3
  win: circleci/windows@5.0

parameters:
  src-repo-url:
    type: string
    default: https://github.com/esnet/iperf.git
  branch-name:
    type: string
    default: "3.8.1"
  common-build-params:
    type: string
    default: "--disable-shared --disable-static"

jobs:
  build-windows:
    executor: win/server-2022
    resource_class: windows.medium
    steps:
      - run:
            name: Install cmake
            command: choco install cmake
      - run:
            name: Install ninja
            command: choco install ninja
      - run:
            name: Checkout dorito
            command: git clone --recurse-submodules "$CIRCLE_REPOSITORY_URL"
      - run:
            name: Configure dorito
            working_directory: dorito
            command: |
                mkdir build
                cd build
                cmake -G Ninja ..
      - run:
            name: Build dorito
            working_directory: dorito/build
            command: ninja
                
      - run:
            name: Package dorito
            working_directory: dorito/build
            command: ninja package
            
      - persist_to_workspace:
          root: .
          paths:
            - Dorito-0.5.0-win32.zip

      - store_artifacts:
          path: Dorito-0.5.0-win32.zip

  build-macos:
    macos:
      xcode: 13.4.1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run:
            name: Install cmake
            command: brew install cmake
      - run:
            name: Install ninja
            command: brew install ninja
      - run:
            name: Checkout dorito
            command: git clone --recurse-submodules "$CIRCLE_REPOSITORY_URL"
      - run:
            name: Configure dorito
            working_directory: dorito
            command: |
                mkdir build
                cd build
                cmake -G Ninja ..
      - run:
            name: Build dorito
            working_directory: dorito/build
            command: ninja
                
      - run:
            name: Package dorito
            working_directory: dorito/build
            command: ninja package
            
      - persist_to_workspace:
          root: .
          paths:
            - Dorito-0.5.0-Darwin.dmg

      - store_artifacts:
          path: Dorito-0.5.0-Darwin.dmg

workflows:
  version: 2
  build-release:
    jobs:
      - build-windows
      - build-macos
